import React from "react";
import {
  View as ViewComponent,
  Text as TextComponent,
  ScrollView as ScrollViewComponent,
  TouchableOpacity as TouchableOpacityComponent,
  SafeAreaView as SafeAreaViewComponent,
  Platform,
  StatusBar
} from "react-native";
// @ts-ignore
import { useRouter } from "expo-router";
import { ArrowLeft as ArrowLeftIcon, FileText as FileTextIcon, AlertTriangle as AlertTriangleIcon } from "lucide-react-native";

const View = ViewComponent as any;
const Text = TextComponent as any;
const ScrollView = ScrollViewComponent as any;
const TouchableOpacity = TouchableOpacityComponent as any;
const SafeAreaView = SafeAreaViewComponent as any;

const ArrowLeft = ArrowLeftIcon as any;
const FileText = FileTextIcon as any;
const AlertTriangle = AlertTriangleIcon as any;

export default function TermsOfUsePage() {
  const router = useRouter();

  return (
    <SafeAreaView className="flex-grow bg-[#f9fafb]">
      <StatusBar barStyle="dark-content" backgroundColor="#f9fafb" />
      
      {/* Header */}
      <View className="flex-row items-center px-5 py-4 border-b border-gray-100 bg-white">
        <TouchableOpacity
          onPress={() => router.back()}
          className="w-10 h-10 rounded-full bg-gray-50 justify-center items-center mr-4 border border-gray-100"
        >
          <ArrowLeft size={20} color="#0f3a31" />
        </TouchableOpacity>
        <View>
          <Text className="text-xl font-extrabold text-[#0f3a31]">Terms of Use</Text>
          <Text className="text-[10px] font-bold text-[#7c8a87] uppercase tracking-wider">FIM App · Vignova</Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={{ padding: 20 }} className="flex-1">
        <View className="mb-6">
          <Text className="text-xs text-[#7c8a87] font-semibold leading-relaxed">
            Effective Date: June 20, 2026 {"\n"}
            Last Updated: June 20, 2026
          </Text>
          <Text className="text-sm text-[#0f3a31] mt-3 font-semibold leading-relaxed">
            Welcome to FIM (Financial Intelligence Manager). By accessing or using our mobile application, you agree to be bound by these Terms of Use. If you do not agree, please do not use the application.
          </Text>
        </View>

        {/* 1. Services & Scope */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">1. Description of Service</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed">
            FIM is a financial planning, interest optimization, and tracking application designed to help users log their EMIs, incomes, expenses, and savings goals manually. We provide amortization schedule visualizations and automated reminder logs.
          </Text>
        </View>

        {/* 2. No Professional Advisory Disclaimer */}
        <View className="bg-amber-50 border border-amber-100 rounded-3xl p-5 mb-6 shadow-sm">
          <View className="flex-row items-center mb-3">
            <AlertTriangle size={22} color="#b45309" className="mr-2" />
            <Text className="text-sm font-extrabold text-[#b45309]">Not Financial Advice</Text>
          </View>
          <Text className="text-xs text-amber-800 font-semibold leading-relaxed">
            All calculations, projections, repayment strategies, and responses generated by the "Ask FIM AI Assistant" are for informational and educational purposes only.
            {"\n\n"}
            FIM is NOT a registered financial planner, investment advisor, bank, or lender. You should consult a certified financial advisor before acting on any metrics, calculations, or suggestions shown in this app.
          </Text>
        </View>

        {/* 3. User Responsibility & Data Entry */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">3. User Responsibility</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed mb-2">
            By registering, you represent that:
          </Text>
          <View className="space-y-2 pl-2">
            <Text className="text-xs text-[#52605d] leading-relaxed font-semibold">
              • All input information (income, EMI details, interest percentages) is correct.
            </Text>
            <Text className="text-xs text-[#52605d] leading-relaxed font-semibold">
              • You will not use the app to submit fraudulent bank account formats.
            </Text>
            <Text className="text-xs text-[#52605d] leading-relaxed font-semibold">
              • You are responsible for keeping your login password and authentication OTP secure.
            </Text>
          </View>
        </View>

        {/* 4. Payment Simulation & Subscriptions */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">4. Payment Simulations</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed">
            Subscription upgrades (such as FIM Premium) may use simulation channels or Razorpay developer sandboxes. Where actual subscription services are enabled, pricing, billing periods, and renewal schedules will be explicitly itemized during the checkout phase.
          </Text>
        </View>

        {/* 5. Limitation of Liability */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">5. Limitation of Liability</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed">
            In no event shall Vignova Technologies, its developers, or its partners be held liable for any direct, indirect, incidental, or special damages, including loss of savings, data corruption, calculation variance, or investment decisions resulting from the use or inability to use FIM.
          </Text>
        </View>

        {/* 6. Governing Law & Dispute Resolution */}
        <View className="mb-12 border-t border-gray-200 pt-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">6. Governing Law</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed">
            These terms are governed by and construed in accordance with the laws of India. Any litigation or legal claims arising under these terms shall be subject to the exclusive jurisdiction of the competent courts in India.
            {"\n\n"}
            If you have questions, please reach out to us at <Text className="font-bold text-[#0f3a31]">vignova.official@gmail.com</Text>.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
