import React from "react";
import {
  View as ViewComponent,
  Text as TextComponent,
  ScrollView as ScrollViewComponent,
  TouchableOpacity as TouchableOpacityComponent,
  SafeAreaView as SafeAreaViewComponent,
  Platform,
  StatusBar
} from "react-native";
// @ts-ignore
import { useRouter } from "expo-router";
import { ArrowLeft as ArrowLeftIcon, FileText as FileTextIcon, AlertTriangle as AlertTriangleIcon, Info as InfoIcon, ShieldAlert as ShieldAlertIcon } from "lucide-react-native";

const View = ViewComponent as any;
const Text = TextComponent as any;
const ScrollView = ScrollViewComponent as any;
const TouchableOpacity = TouchableOpacityComponent as any;
const SafeAreaView = SafeAreaViewComponent as any;

const ArrowLeft = ArrowLeftIcon as any;
const FileText = FileTextIcon as any;
const AlertTriangle = AlertTriangleIcon as any;
const Info = InfoIcon as any;
const ShieldAlert = ShieldAlertIcon as any;

export default function TermsOfUsePage() {
  const router = useRouter();

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: "#f9fafb" }}>
      <StatusBar barStyle="dark-content" backgroundColor="#f9fafb" />
      
      {/* Header */}
      <View className="flex-row items-center px-5 py-4 border-b border-gray-100 bg-white">
        <TouchableOpacity
          onPress={() => router.back()}
          className="w-10 h-10 rounded-full bg-gray-50 justify-center items-center mr-4 border border-gray-100"
        >
          <ArrowLeft size={20} color="#0f3a31" />
        </TouchableOpacity>
        <View>
          <Text className="text-xl font-extrabold text-[#0f3a31]">Terms of Use</Text>
          <Text className="text-[10px] font-bold text-[#7c8a87] uppercase tracking-wider">FIM App · Vignova</Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 40 }} style={{ flex: 1 }}>
        <View className="mb-6">
          <Text className="text-xs text-[#7c8a87] font-semibold leading-relaxed">
            Effective Date: June 20, 2026 {"\n"}
            Last Updated: June 28, 2026
          </Text>
          <Text className="text-sm text-[#0f3a31] mt-3 font-semibold leading-relaxed">
            Welcome to FIM (Financial Intelligence Manager). By downloading, accessing, or using our mobile application, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not install or use the application.
          </Text>
        </View>

        {/* 1. Scope of Service & Non-Transaction Nature */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">1. Description of Service</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed mb-2">
            FIM is a personal financial tracking, calculation, and planning application. The service allows users to manually log and organize their financial data, including EMI repayment schedules, monthly incomes, daily expenses, and savings goals.
          </Text>
          <View className="bg-emerald-50 border border-emerald-100 rounded-2xl p-4 mb-3 flex-row items-start">
            <Info size={18} color="#059669" className="mr-3 mt-0.5" />
            <View className="flex-1">
              <Text className="font-bold text-emerald-800 text-xs">Manual Tracking Only</Text>
              <Text className="text-[10px] text-emerald-700 mt-1 font-semibold leading-relaxed">
                FIM does **NOT** disburse loans, facilitate credit, offer lending services, or connect to actual bank accounts. The "Mark paid" and "Record Payment" buttons are purely bookkeeping actions to help you keep track of your finances manually. No real-world money is transferred or processed by clicking these buttons.
              </Text>
            </View>
          </View>
        </View>

        {/* 2. No Professional Advisory Disclaimer */}
        <View className="bg-amber-50 border border-amber-100 rounded-3xl p-5 mb-6 shadow-sm">
          <View className="flex-row items-center mb-3">
            <AlertTriangle size={22} color="#b45309" className="mr-2" />
            <Text className="text-sm font-extrabold text-[#b45309]">No Financial or Legal Advice</Text>
          </View>
          <Text className="text-xs text-amber-800 font-semibold leading-relaxed">
            All calculations, interest projections, repayment timelines, and responses generated by the **"Ask FIM AI Assistant"** (powered by Google Gemini) are simulations designed for informational and educational purposes only.
            {"\n\n"}
            FIM and Vignova Technologies are **not** registered financial planners, investment advisors, banks, brokers, or lenders. The metrics and recommendations shown in this app should not be treated as professional advice. You must consult a certified financial advisor before making any refinancing, prepayment, or investment decisions.
          </Text>
        </View>

        {/* 3. User Eligibility & Account Security */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">3. User Responsibilities & Account Security</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed mb-2">
            By creating an account on FIM, you agree to the following terms:
          </Text>
          <View className="space-y-3 pl-2">
            <View>
              <Text className="text-xs text-[#0f3a31] font-bold">• Data Accuracy:</Text>
              <Text className="text-xs text-[#52605d] leading-relaxed font-semibold pl-3">
                You are solely responsible for entering accurate information regarding your loans, interest rates, incomes, and expenses. The accuracy of all schedules and AI insights depends entirely on the data you provide.
              </Text>
            </View>
            <View>
              <Text className="text-xs text-[#0f3a31] font-bold">• Credential Confidentiality:</Text>
              <Text className="text-xs text-[#52605d] leading-relaxed font-semibold pl-3">
                You must keep your account password and verification OTP confidential. Any activity that occurs under your account is your sole responsibility. If you suspect unauthorized access, you must notify us immediately.
              </Text>
            </View>
            <View>
              <Text className="text-xs text-[#0f3a31] font-bold">• Prohibited Use:</Text>
              <Text className="text-xs text-[#52605d] leading-relaxed font-semibold pl-3">
                You agree not to use the application to log fraudulent, misleading, or illegal data. You are prohibited from reverse-engineering, hacking, or attempting to compromise the security of the FIM servers or APIs.
              </Text>
            </View>
          </View>
        </View>

        {/* 4. Subscriptions & Payment Simulations */}
        <View className="mb-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">4. Subscriptions & Premium Features</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed">
            FIM offers optional premium features (such as FIM Premium) that provide unlimited tracking, advanced AI refinancing alerts, and unlimited chatbot queries. 
            {"\n\n"}
            During local testing or review, payment gateways (like Razorpay) may run in **sandbox/test mode** where no real money is charged. When live subscriptions are enabled, billing terms, cancellation policies, and renewal schedules will be clearly displayed during checkout. You may cancel your subscription at any time.
          </Text>
        </View>

        {/* 5. Limitation of Liability & Warranties */}
        <View className="bg-white border border-[#e5e7eb] rounded-3xl p-5 mb-6 shadow-sm">
          <View className="flex-row items-center mb-3">
            <ShieldAlert size={20} color="#0f4a3f" className="mr-2" />
            <Text className="text-sm font-extrabold text-[#0f3a31]">Disclaimer of Warranties</Text>
          </View>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed mb-3">
            FIM is provided on an **"as is"** and **"as available"** basis, without warranties of any kind, either express or implied, including but not limited to the accuracy of interest calculations, amortization tables, or notification delivery times.
          </Text>
          <Text className="text-xs text-[#0f3a31] font-bold">Limitation of Liability:</Text>
          <Text className="text-xs text-[#52605d] leading-relaxed font-semibold pl-2 mt-1">
            In no event shall Vignova Technologies, its developers, or its partners be held liable for any direct, indirect, incidental, or special damages, including but not limited to:
            {"\n"}• Interest penalties or late fees charged by your real-world lenders.
            {"\n"}• Investment losses or decisions made based on the AI assistant’s advice.
            {"\n"}• Data loss or calculation variances caused by server interruptions or bugs.
          </Text>
        </View>

        {/* 6. Governing Law & Dispute Resolution */}
        <View className="mb-12 border-t border-gray-200 pt-6">
          <Text className="text-base font-extrabold text-[#0f3a31] mb-2">6. Governing Law & Jurisdiction</Text>
          <Text className="text-xs text-[#52605d] font-semibold leading-relaxed">
            These Terms of Use are governed by and construed in accordance with the laws of India. Any legal claims, disputes, or litigation arising out of or in connection with the use of FIM shall be subject to the exclusive jurisdiction of the competent courts in India.
            {"\n\n"}
            If you have any questions regarding these terms, please contact us at:
            {"\n\n"}
            <Text className="font-extrabold text-[#0f3a31]">Vignova Technologies</Text>
            {"\n"}
            Email: <Text className="text-emerald-600 font-bold">vignova.official@gmail.com</Text>
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
